sudo: required

language: node_js

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.11.2

#install: true

before_install:
  - git clone https://github.com/OpenChirp/server_docker.git 
  - cd server_docker
  - docker-compose -f docker-compose.yml -f docker-compose.test-rest.yml up -d
  - cd ..
