sudo: required

language: node_js

node_js:
  - "7"
  
services:
  - docker

before_install:
  - git clone https://github.com/OpenChirp/server_docker.git 
  - cd server_docker
  - docker-compose -f docker-compose.yml -f docker-compose.test-rest.yml up -d
  - cd ..
  - wget https://raw.githubusercontent.com/OpenChirp/server_docker/master/node/config/test.json -o config/test.json
  
