sudo: required

language: node_js

node_js:
  - "7"
  
services:
  - docker

before_install:
  - cd ..
  - git clone https://github.com/OpenChirp/server_docker.git 
  - cd server_docker
  - git clone https://github.com/nampereira/openchirp_rest.git ./node/code
  - docker-compose -f docker-compose.yml -f docker-compose.test-rest.yml up -d
  - cd ..
install: true

script: cd server_docker && docker exec -it serverdocker_rest_1 npm install && && docker exec -it serverdocker_rest_1 npm test

