sudo: required

language: node_js

node_js:
  - "7"
  
services:
  - docker

before_install:
  - git clone https://github.com/OpenChirp/server_docker.git 
  - cp ./server_docker/node/config/docker.json config/test.json
  - cat config/test.json 
  - cd server_docker
  - docker-compose -f docker-compose.yml -f docker-compose.test-rest.yml up -d
  - cd ..
  
install: true

script: cd server_docker && docker exec -it serverdocker_rest_1 npm test

