sudo: required

language: node_js

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.11.2

install: true

before_install:
  - docker --version
  - docker-compose --version
  - git clone --depth=50 --branch=master https://github.com/OpenChirp/server_docker.git 
